# Generated by Django 5.1.7 on 2025-03-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='participants_registered',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
