# Generated by Django 5.1.7 on 2025-03-30 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=256)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_activities', to='db.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_activities', to='db.teamprofile')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_activities', to='db.teammember')),
            ],
        ),
    ]
