# Generated by Django 5.1.7 on 2025-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_participantactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantactivity',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
