# Generated by Django 5.1.7 on 2025-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_participantactivity_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonsettings',
            name='max_score',
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='easy_max_score',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='hard_max_score',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='medium_max_score',
            field=models.IntegerField(default=300),
        ),
    ]
