# Generated by Django 5.1.7 on 2025-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
