# Generated by Django 5.1.7 on 2025-03-12 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_question_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_team_size', models.PositiveIntegerField(default=4)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('has_started', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hackathon Settings',
            },
        ),
    ]
