# Generated by Django 5.1.7 on 2025-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_hackathonsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonsettings',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='time_paused',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='time_resumed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
