# Generated by Django 5.1.7 on 2025-03-12 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_hackathonsettings_is_paused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonsettings',
            name='time_resumed',
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='time_spent_paused',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
