# Generated by Django 5.1.7 on 2025-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_hackathonsettings_time_resumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='team_password',
            field=models.CharField(default='Test1234', max_length=100),
            preserve_default=False,
        ),
    ]
