# Generated by Django 5.1.7 on 2025-03-12 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_teamprofile_team_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonsettings',
            name='max_score',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='score_decrement_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='score_decrement_per_interval',
            field=models.IntegerField(default=1),
        ),
    ]
