# Generated by Django 5.1.7 on 2025-03-12 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_answer_time_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonsettings',
            name='score_decrement_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AlterField(
            model_name='hackathonsettings',
            name='score_decrement_per_interval',
            field=models.IntegerField(default=10),
        ),
    ]
