# Generated by Django 5.1.7 on 2025-03-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_hackathonsettings_score_decrement_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='team',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='db.teamprofile'),
            preserve_default=False,
        ),
    ]
