# Generated by Django 5.1.7 on 2025-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_submitted',
            field=models.DateTimeField(),
        ),
    ]
