# Generated by Django 5.1.7 on 2025-03-22 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_answer_time_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('time_shared', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_code', to='db.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_code', to='db.teamprofile')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_code', to='db.teammember')),
            ],
        ),
    ]
