# Generated by Django 5.1.7 on 2025-03-22 22:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_sharedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcode',
            name='file_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
